spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

logging:
  level:
    p6spy: info
#    org.hibernate.sql: debug
#    org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true